services:
  postgres:
    image: postgres:15
    container_name: db
    environment:
      POSTGRES_DB: challenge
      POSTGRES_USER: user
      POSTGRES_PASSWORD: pass
    ports:
      - "5432:5432"
  app:
    image: jeanpier39/challenge-app:1.0
    container_name: challenge-app
    ports:
      - "8080:8080"
    depends_on:
      - postgres
    environment:
      SPRING_DATASOURCE_URL: "jdbc:postgresql://postgres:5432/challenge"
      SPRING_DATASOURCE_USERNAME: "user"
      SPRING_DATASOURCE_PASSWORD: "pass"